### ISSUE TITLE
Enhancement: add title+description and photo viewer

### ISSUE THREAD

**Issue by scramatte** [ArdentHQ/nova-image-gallery-field#20]
Hi,

Can you add support for title+description and photo viewer?

This component is nice
https://silentbox.rocek.dev/

Regards

**Comment by scramatte** [comment]
I've made PR #22 to add support for lightbox

**Comment by ItsANameToo** [comment]
Lightbox support has been added in #23 and released with 1.1.0 @scramatte

Title and description are not something that would fit our use case for the package at the moment, but you're free to open a PR for that to make it a configurable setting to show it
