### ISSUE TITLE
An error occured while uploading your file...

### ISSUE THREAD

**Issue by scramatte** [ArdentHQ/nova-image-gallery-field#51]
Hello,

I've tried to upload pdf and svg files but I've got  the following message: "An error occured while uploading your file"
I don't see any error in Laravel log file.

How can I troubleshoot this?

Regards

**Comment by wajdijurry** [comment]
@scramatte  Check your web console for errors

**Comment by scramatte** [comment]
Nothing appears in the console.  I believe that the field support only images. Because when you try to pick  pdf or svg files they are greyed out in the list.

**Comment by ItsANameToo** [comment]
At the moment it only supports PNG and JPG images. We're open to a PR that adds SVG support, but PDF will be out of scope for the image gallery field package
