### ISSUE TITLE
Use Spatie Media Convertion?

### ISSUE THREAD

**Issue by scramatte** [ArdentHQ/nova-image-gallery-field#53]
Hi,

I've registered a collection and a convertion into my model.
It  looks that nova-image-gallery-field doesn't use  thumbnail convertion.

Can you help?

Regards

**Comment by ItsANameToo** [comment]
Can you provide some code that highlights the issue you're experiencing and what you expect from it?

**Comment by ItsANameToo** [comment]
closing this due to lack of response, can be reopened with a reproduction example
