### ISSUE TITLE
Unable to rebuild component locally 

### ISSUE THREAD

**Issue by scramatte** [ArdentHQ/nova-image-gallery-field#54]
Hi,

I need to make a PR but I'm unable to rebuild locally component.
Can you give me an hand?

![imagen](https://github.com/ArdentHQ/nova-image-gallery-field/assets/188766/2438b454-fb33-4069-8aad-70c58264760c)

I've edited nova.mix.js  and I change path to laravel-nova  else it neither found  nova components.

![imagen](https://github.com/ArdentHQ/nova-image-gallery-field/assets/188766/67aa81cd-8c7e-44f0-b456-fa55ccd18116)

I've added  "../../" before path...
```
            "laravel-nova": path.join(
                __dirname,
                "../../vendor/laravel/nova/resources/js/mixins/packages.js"
            ), 
```

**Comment by ItsANameToo** [comment]
Can you provide the steps you took to install it locally and what you run that causes the above issue?

**Comment by ItsANameToo** [comment]
closing this due to lack of response, can be reopened with a reproduction example
